basePath: /
definitions:
  models.APIError:
    properties:
      message:
        type: string
    type: object
  models.Agenda:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  models.Alert:
    properties:
      agenda_id:
        type: string
      condition:
        description: e.g., "always", "room_change"
        type: string
      id:
        type: string
      target:
        description: e.g., email address
        type: string
    type: object
  models.User:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    name: Morty
    url: http://localhost:8080/swagger/index.html
  description: 'API de configuration : agendas & alerts (CRUD).'
  title: Unicorn â€“ Config API
  version: "1.0"
paths:
  /agendas:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Agenda'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.APIError'
      summary: List agendas
      tags:
      - agendas
    post:
      consumes:
      - application/json
      parameters:
      - description: Agenda
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Agenda'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Agenda'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Create agenda
      tags:
      - agendas
  /agendas/{id}:
    delete:
      parameters:
      - description: Agenda ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Delete agenda
      tags:
      - agendas
    get:
      parameters:
      - description: Agenda ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Agenda'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Get agenda by id
      tags:
      - agendas
    put:
      consumes:
      - application/json
      parameters:
      - description: Agenda ID
        in: path
        name: id
        required: true
        type: string
      - description: Agenda
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Agenda'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Agenda'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Update agenda
      tags:
      - agendas
  /alerts:
    get:
      parameters:
      - description: Filter by agenda id
        in: query
        name: agenda_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Alert'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIError'
      summary: List alerts (optional filter by agenda_id)
      tags:
      - alerts
    post:
      consumes:
      - application/json
      parameters:
      - description: Alert
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Alert'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Alert'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Create alert
      tags:
      - alerts
  /alerts/{id}:
    delete:
      parameters:
      - description: Alert ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Delete alert
      tags:
      - alerts
    get:
      parameters:
      - description: Alert ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Alert'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Get alert by id
      tags:
      - alerts
    put:
      consumes:
      - application/json
      parameters:
      - description: Alert ID
        in: path
        name: id
        required: true
        type: string
      - description: Alert
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Alert'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Alert'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Update alert
      tags:
      - alerts
  /users:
    get:
      description: Get all users.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Something went wrong
      summary: Get all users.
      tags:
      - users
  /users/{id}:
    get:
      description: Get a user.
      parameters:
      - description: User UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Get a user.
      tags:
      - users
schemes:
- http
swagger: "2.0"
